version: '{build}'

matrix:
  fast_finish: true

environment:
  matrix:
    - NIM_ARCHIVE: nim-1.0.0_x64.zip
      NIM_DIR: nim-1.0.0
      NIM_URL: https://nim-lang.org/download/nim-1.0.0_x64.zip
      MINGW_PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
      BEARLIB_ARCHIVE: bearlibterminal_0.15.7.zip
      BEARLIB_URL: http://foo.wyrd.name/_media/en:bearlibterminal:bearlibterminal_0.15.7.zip
      platform: x64

cache:
  - '%NIM_ARCHIVE% -> .appveyor.yml'
  - '%BEARLIB_ARCHIVE% -> .appveyor.yml'

install:
  - SET PATH=%MINGW_PATH%;%PATH%
  - FOR /f %%G IN ('git describe') DO SET BUILD_VERSION=%%G

  # Install Nim
  - MKDIR %CD%\tools_tmp
  - IF not exist "%NIM_ARCHIVE%" appveyor DownloadFile "%NIM_URL%" -FileName "%NIM_ARCHIVE%"
  - 7z x -y "%NIM_ARCHIVE%" -o"%CD%\tools_tmp"> nul
  - SET PATH=%CD%\tools_tmp\%NIM_DIR%\bin;%PATH%

  # Install BearLib
  - IF not exist "%CD%\lib\" MKDIR "CD%\lib"
  - IF not exist "%BEARLIB_ARCHIVE%" appveyor DownloadFile "%BEARLIB_URL%" -FileName "%BEARLIB_ARCHIVE%"
  - 7z x -y "%BEARLIB_ARCHIVE%" -o"%CD%\lib"> nul
  - COPY /Y lib\BearLibTerminal_0.15.7\Windows64\BearLibTerminal.dll libBearLibTerminal.dll

build_script:
  - nimble.exe buildRelease

after_build:
  - 7z a slnselector_%BUILD_VERSION%.zip slnselector.exe libBearLibTerminal.dll

artifacts:
  - path: slnselector_%BUILD_VERSION%.zip
    name: slnselector

test_script:
  - nimble.exe test

deploy: off